export const API_URLS = {
  LOGIN: "/auth/login",
  USER_DETAILS: "/auth/details",
  FRANCHISE_GET_ALL: "/franchise",
  FRANCHISE_CREATE: "/franchise/create",
  FRANCHISE_GET_BY_ID: "/franchise",
  FRANCHISE_EDIT: "/franchise",
  FRANCHISE_DELETE: "/franchise",
  GYM_GET_ALL: "/gym",
  GYM_CREATE: "/gym/create",
  GYM_GET_BY_ID: "/gym",
  GYM_EDIT: "/gym",
  GYM_DELETE: "/gym",
  MEMBERSHIP_GET_ALL: "/memberships",
  MEMBERSHIP_GET_BY_ID: "/memberships",
  MEMBERSHIP_CREATE: "/memberships",
  MEMBERSHIP_UPDATE: "/memberships",
  MEMBERSHIP_DELETE: "/memberships",
  MEMBERSHIP_IMPORT: "/memberships/bulk-import",
  TRAINER_GET_ALL:"/trainer",
  TRAINER_CREATE:"/trainer/create",
  TRAINER_GET_BY_ID:"/trainer",
  TRAINER_EDIT:"/trainer",
  TRAINER_DELETE:"/trainer",
  MEMBER_GET_ALL:"/member",
  MEMBER_CREATE:"/member/create",
  MEMBER_GET_BY_ID:"/member",
  MEMBER_EDIT:"/member",
  MEMBER_DELETE:"/member",
  WORKOUT_GET_ALL: "/workouts",
  WORKOUT_CREATE: "/workouts/create",
  WORKOUT_GET_BY_ID: "/workouts",
  WORKOUT_EDIT: "/workouts",
  WORKOUT_DELETE: "/workouts",
  WORKOUT_ASSIGN:"/workouts/assign-plan",
  DIET_PLAN_GET_ALL:"/dietplans",
  DIET_PLAN_CREATE:"/dietplans",
  DIET_PLAN_GET_BY_ID:"/dietplans",
  DIET_PLAN_EDIT:"/dietplans",
  DIET_PLAN_DELETE:"/dietplans",
  ASSIGN_DIET_PLAN:"/assign-diet-plan",
  CHECKIN_CHECKOUT:"/member/checkincheckout",
  LOGGED_TIME:"/member/loggedtime",
  FRANCHISE_GET_DUES:"/franchise/duesubscriptions/:id",
  FRANCHISE_RECORD_PAYMENT:"/franchise/payments",
  MEMBER_DUE_FEES:"/member/due-payments",
  MEMBER_FEES_PAYMENT:"/member/mark-payment"
};
